version: "3.7"

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:5.5.3
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - "2181:2181"

    kafka1:
        image: confluentinc/cp-kafka:5.5.3
        container_name: kafkaavro1
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

            # 2 listeners: internal (docker network) + external (localhost)
            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:19092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
        ports:
            - "9092:19092"

    kafka2:
        image: confluentinc/cp-kafka:5.5.3
        container_name: kafkaavro2
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:19093
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093,PLAINTEXT_HOST://localhost:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
        ports:
            - "9093:19093"

    kafka3:
        image: confluentinc/cp-kafka:5.5.3
        container_name: kafkaavro3
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 3
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

            KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094,PLAINTEXT_HOST://0.0.0.0:19094
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094,PLAINTEXT_HOST://localhost:9094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
        ports:
            - "9094:19094"

    schema-registry:
        image: confluentinc/cp-schema-registry:5.5.3
        depends_on:
            - zookeeper
            - kafka1
            - kafka2
            - kafka3
        environment:
            SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
        ports:
            - "8081:8081"

    kafdrop:
        image: obsidiandynamics/kafdrop:latest
        container_name: kafdrop1
        depends_on:
            - kafka1
            - kafka2
            - kafka3
        environment:
            KAFKA_BROKERCONNECT: kafka1:9092,kafka2:9093,kafka3:9094
        ports:
            - "9000:9000"