#topic:
#  name: mars
#spring:
#  kafka:
#    bootstrap-servers: "kafka-cluster:9092,kafka-cluster:9093,kafka-cluster:9093"
#    producer:
#      keySerializer: "org.apache.kafka.common.serialization.StringSerializer"
#      valueSerializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
#      properties:
#        schema:
#          registry:
#            url: "http://kafka-cluster:8081"
#    consumer:
#      group-id: "javatechie-new"
#      keyDeserializer: "org.apache.kafka.common.serialization.StringDeserializer"
#      valueDeserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
#      autoOffsetReset: "earliest"
#      properties:
#        schema:
#          registry:
#            url: "http://kafka-cluster:8081"
#        specific:
#          avro:
#            reader: "true"